export {default as HomeView} from './HomeView.vue'
export {default as LoginView} from './LoginView.vue'
export {default as NotFoundView} from './NotFoundView.vue'
export {default as ForgotView} from './ForgotView.vue'
export {default as SignUpView} from './SignUpView.vue'
export {default as UserView} from './UserView.vue'